// <auto-generated/>
//------------------------------------------------------------------------------
// PluginConfiguration.cs
// Copyright (c) Vitrua. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
//------------------------------------------------------------------------------

namespace Jellyfin.Plugin.PosterFlags.Configuration
{
    using MediaBrowser.Model.Plugins;

    /// <summary>
    /// Plugin configuration.
    /// </summary>
    public class PluginConfiguration : BasePluginConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PluginConfiguration"/> class.
        /// </summary>
        public PluginConfiguration()
        {
            // Default settings
            EnableFlagOverlay = true;
        }

        /// <summary>
        /// Gets or sets a value indicating whether the flag overlay feature is enabled.
        /// </summary>
        public bool EnableFlagOverlay { get; set; }
    }
}
